from __future__ import annotations

import secrets
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


BROKER_SCHEMA_VERSION = "1.0"


class MessageKind(str, Enum):
    request = "request"
    contribution = "contribution"
    final_synthesis = "final_synthesis"


class BrokerEnvelope(BaseModel):
    """Host-generated, versioned message envelope for all OACG collaboration hops."""

    model_config = ConfigDict(extra="forbid")

    schema_version: str = Field(default=BROKER_SCHEMA_VERSION)
    trace_id: str = Field(min_length=1, max_length=128)
    message_id: str = Field(min_length=1, max_length=128)
    sender: str = Field(min_length=1, max_length=64, pattern=r"^[a-z0-9_.:-]+$")
    recipient: str = Field(min_length=1, max_length=64, pattern=r"^[a-z0-9_.:-]+$")
    kind: MessageKind
    sequence: int = Field(ge=1)
    created_at: datetime
    deadline_at: datetime | None = None
    nonce: str = Field(min_length=16, max_length=128)
    content: str = Field(min_length=1)
    model: str | None = None
    latency_ms: int | None = Field(default=None, ge=0)
    metadata: dict[str, Any] = Field(default_factory=dict)

    def model_post_init(self, __context: Any) -> None:
        if self.schema_version != BROKER_SCHEMA_VERSION:
            raise ValueError(
                f"unsupported broker schema_version '{self.schema_version}'; "
                f"expected '{BROKER_SCHEMA_VERSION}'"
            )
        if self.deadline_at is not None and self.deadline_at <= self.created_at:
            raise ValueError("deadline_at must be later than created_at")


def new_envelope(
    *,
    trace_id: str,
    sender: str,
    recipient: str,
    kind: MessageKind,
    sequence: int,
    content: str,
    deadline_at: datetime | None = None,
    model: str | None = None,
    latency_ms: int | None = None,
    metadata: dict[str, Any] | None = None,
) -> BrokerEnvelope:
    """Create a broker envelope. IDs/nonces are always generated by the OACG host."""

    return BrokerEnvelope(
        schema_version=BROKER_SCHEMA_VERSION,
        trace_id=trace_id,
        message_id=str(uuid.uuid4()),
        sender=sender,
        recipient=recipient,
        kind=kind,
        sequence=sequence,
        created_at=datetime.now(timezone.utc),
        deadline_at=deadline_at,
        nonce=secrets.token_urlsafe(18),
        content=content,
        model=model,
        latency_ms=latency_ms,
        metadata=metadata or {},
    )
